networks:
  loki: {}
services:
  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    networks:
      loki: null
    ports:
    - published: 8080
      target: 8080
    restart: always
    volumes:
    - /mnt/nas/Mac-files/test/syslog/cadvisor/root/:/rootfs:ro
    - /mnt/nas/Mac-files/test/syslog/cadvisor/var/run:/var/run:rw
    - /mnt/nas/Mac-files/test/syslog/cadvisor/sys:/sys:ro
    - /mnt/nas/Mac-files/test/syslog/cadvisor/var/lib/docker:/var/lib/docker:ro
  node-exporter:
    command: --path.rootfs=/host
    container_name: node-exporter
    image: prom/node-exporter:latest
    networks:
      loki: null
    pid: host
    ports:
    - published: 9100
      target: 9100
    restart: always
    volumes:
    - /mnt/nas/Mac-files/test/syslog/node-exporter/:/host:ro,rslave
  prometheus:
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.tsdb.path=/prometheus
    - --web.enable-admin-api
    - --web.enable-lifecycle
    container_name: prometheus
    image: prom/prometheus:latest
    networks:
      loki: null
    ports:
    - published: 9090
      target: 9090
    restart: always
    volumes:
    - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
  grafana:
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /var/lib/grafana/dashboards/no_folder/loki_syslog_aio_overview.json
    image: grafana/grafana:8.1.2
    networks:
      loki: null
    ports:
    - protocol: tcp
      published: 3100
      target: 3100
    restart: always
    volumes:
    - ./config/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
    - ./config/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
    - ./config/grafana/dashboards:/var/lib/grafana/dashboards:ro
    - /mnt/nas/Mac-files/test/syslog/grafana:/var/lib/grafana
  loki:
    command: -config.file=/etc/loki/loki-config.yml
    container_name: loki
    image: grafana/loki:2.3.0
    networks:
      loki: null
    ports:
    - protocol: tcp
      published: 3200
      target: 3200
    restart: always
    volumes:
    - ./config/loki-config-filesystem.yml:/etc/loki/loki-config.yml:ro
    - /mnt/nas/Mac-files/test/syslog/loki:/tmp/loki/
  promtail:
    command: -config.file=/etc/promtail/promtail-config.yml
    container_name: promtail
    image: grafana/promtail:2.3.0
    networks:
      loki: null
    ports:
    - protocol: tcp
      published: 1519
      target: 1519
    - protocol: tcp
      published: 9081
      target: 9081
    restart: always
    volumes:
    - ./config/promtail-config.yml:/etc/promtail/promtail-config.yml:ro
  syslog-ng:
    command: -edv
    container_name: syslog-ng
    depends_on:
    - promtail
    image: balabit/syslog-ng:latest
    networks:
      loki: null
    ports:
    - protocol: udp
      published: 516
      target: 516
    - protocol: tcp
      published: 608
      target: 608
    restart: always
    volumes:
    - ./config/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf:ro
version: '3.3'
